/**
 * Dicionário unificado de tradução de Traits / Subtipos de One Piece Card Game.
 * Fonte única da verdade compartilhada entre os scripts de ingestão e compilação.
 */
export const TRAIT_TRANSLATIONS = {
  'Straw Hat Crew': 'Bando do Chapéu de Palha',
  'Worst Generation': 'Pior Geração',
  'Supernovas': 'Supernovas',
  'Heart Pirates': 'Piratas do Coração',
  'Kid Pirates': 'Piratas do Kid',
  'Whitebeard Pirates': 'Piratas do Barba Branca',
  'Navy': 'Marinha',
  'The Four Emperors': 'Quatro Imperadores',
  'Four Emperors': 'Quatro Imperadores',
  'Land of Wano': 'País de Wano',
  'Kouzuki Clan': 'Clã Kouzuki',
  'Kurozumi Clan': 'Clã Kurozumi',
  'Animal Kingdom Pirates': 'Piratas das Feras',
  'Big Mom Pirates': 'Piratas da Big Mom',
  'The Seven Warlords of the Sea': 'Sete Corsários',
  'Seven Warlords of the Sea': 'Sete Corsários',
  'Revolutionary Army': 'Exército Revolucionário',
  'Dressrosa': 'Dressrosa',
  'Donquixote Pirates': 'Piratas Donquixote',
  'Fish-Man': 'Homem-Peixe',
  'Merfolk': 'Tritão',
  'Mink Tribe': 'Tribo Mink',
  'Egghead': 'Egghead',
  'CP9': 'CP9',
  'CP0': 'CP0',
  'FILM': 'FILM',
  'East Blue': 'East Blue',
  'Alabasta': 'Alabasta',
  'Skypiea': 'Skypiea',
  'Water Seven': 'Water Seven',
  'Thriller Bark Pirates': 'Piratas de Thriller Bark',
  'Germa 66': 'Germa 66',
  'Baroque Works': 'Baroque Works',
  'Blackbeard Pirates': 'Piratas do Barba Negra',
  'Red-Haired Pirates': 'Piratas do Ruivo',
  'Cross Guild': 'Cross Guild',
  'World Government': 'Governo Mundial',
  'Jailer Beast': 'Besta Carcereira',
  'Impel Down': 'Impel Down',
  'Former Navy': 'Ex-Marinha',
  'Fish-Man Island': 'Ilha dos Homens-Peixe',
  'Punk Hazard': 'Punk Hazard',
  'Giants': 'Gigantes',
  'Giant': 'Gigante',
  'Amazon Lily': 'Amazon Lily',
  'Kuja Pirates': 'Piratas Kuja',
  'Jaya': 'Jaya',
  'Mighty Atomics': 'Mighty Atomics',
  'Scientist': 'Cientista',
  'Neo Navy': 'Neo Marinha',
  'Baterilla': 'Baterilla',
  'Windmill Village': 'Vila Moinho de Vento',
  'Sun Pirates': 'Piratas do Sol',
  'Roger Pirates': 'Piratas do Roger',
  'Mugiwara Chase': 'Mugiwara Chase',
  'Kingdom of Prodence': 'Reino de Prodence',
  'Goa Kingdom': 'Reino de Goa',
  'Foxy Pirates': 'Piratas Foxy',
  'Buggy Pirates': 'Piratas do Buggy',
  'Arlong Pirates': 'Piratas do Arlong',
  'Krieg Pirates': 'Piratas do Krieg',
  'Black Cat Pirates': 'Piratas do Gato Preto',
  'Fishman': 'Homem-Peixe',
  'Animal': 'Animal',
  'Pirates': 'Piratas',
  'Mountain Bandits': 'Bandidos da Montanha',
  'Elbaph': 'Elbaf',
  'Elbaf': 'Elbaf',
  'New Giant Pirates': 'Novos Piratas Gigantes',
  'Firetank Pirates': 'Piratas Firetank',
  'Former Big Mom Pirates': 'Ex-Piratas da Big Mom',
  'SMILE': 'SMILE'
};

/**
 * Traduz um trait do inglês para o português, ou retorna o original caso não haja tradução cadastrada.
 * @param {string} trait
 * @returns {string}
 */
export function translateTrait(trait) {
  return TRAIT_TRANSLATIONS[trait] || trait;
}
